name: Build Vlang Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install V
      run: |
        git clone --depth=1 https://github.com/vlang/v
        cd v
        make

    - name: Build V Module
      run: |
        ./v . -prod