name: Build Vlang Module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install V
      run: |
        git clone --depth=1 https://github.com/vlang/v
        cd v
        make

    - name: Build V Module
      run: |
        ./v/v . -prod

    - name: Upload Module
      uses: actions/upload-artifact@v4
      with:
        name: ffn-linux
        path: ./ffn
        if-no-files-found: 'warn'

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install V
      run: |
        git clone --depth=1 https://github.com/vlang/v
        cd v
        ./make.bat

    - name: Build V Module
      run: |
        ./v/v.exe . -prod

    - name: Upload Module
      uses: actions/upload-artifact@v4
      with:
        name: ffn-windows
        path: ./ffn.exe
        if-no-files-found: 'warn'